[_]
schema-version = "0.2"

[io.buildpacks.build.env]
GOOGLE_GO_VERSION = "1.23"
GO111MODULE = "on"
GOPROXY = "https://proxy.golang.org"

[[io.buildpacks.group]]
id = "google.go.runtime"

[[io.buildpacks.group]]
id = "google.go.gopath"

[[io.buildpacks.group]]
id = "google.go.build"

[[io.buildpacks.group]]
id = "google.utils.label-image"